- hosts: kali_linux
  user: ray
  become: true
  vars:
    site_item: 
    - prod.sitelocal.com
  tasks:

    - name: Install apache2
      apt:
        name: ['apache2']
        state: present

    - name: Start apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create web root directory
      file:
        path: /var/www/{{site_item}}
        state: directory
        mode: 0755

    - name: Copy custom index.html file
      copy:
        src: index.html
        dest: /var/www/{{ site_item }}/index.html
        owner: root
        group: root
        mode: 0644

    - name: Edit index.html of {{ site_item }}
      lineinfile:
        dest: /var/www/{{ site_item }}/index.html
        insertafter: <body>
        line: '<h1>Welcome {{ site_item }} </h1>'

    - name: Config {{ site_item }}.conf
      template:
        src: "{{ playbook_dir }}/template.conf.j2"
        dest: /etc/apache2/sites-available/{{ site_item }}.conf

    - name: Link configuration to enabled
      file:
        src: /etc/apache2/sites-available/{{ site_item }}.conf
        dest: /etc/apache2/sites-enabled/{{ site_item }}.conf
        state: link

    - name: Add servername in hosts file
      lineinfile:
        dest: /etc/hosts
        line: '192.168.214.187  {{ site_item }}'

    - name: Reload apache2
      service:
        name: apache2
        state: reloaded
