---
- hosts: host2
  user: ray
  vars_files:
    - list.yml
    # file_content: "{{ lookup('fileglob', 'list.txt', wantList=true) }}"

  tasks:

    # - name: Copy list test 
    #   template:
    #     src: "{{ playbook_dir }}/list.txt"
    #     dest: /home/ray/list.txt

    # - name: test1 
    #   debug: msg="{{ item }}"
    #   with_items: '{{ site }}'

    - name: Config test.conf
      template:
        src: "{{ playbook_dir }}/template_test.conf.j2"
        dest: /home/ray/{{ item }}.conf
      with_items: '{{ site }}'

    - name: Create directory enabled
      file:
        path: /home/ray/enabled
        state: directory

    - name: Link configuration to enabled
      file:
        src: /home/ray/{{ item }}.conf
        dest: /home/ray/enabled/{{ item }}.conf
        state: link
      with_items:
      - "{{ site }}"
