---
- hosts: kali_linux
  user: ray
  vars:
    all_item:
      src: "{{ playbook_dir }}/list.txt"
  tasks:

    - name: Config test.conf
      template:
        src: "{{ playbook_dir }}/template_test.conf.j2"
        dest: /home/ray/{{ item }}.conf
      with_items:
      - "{{ all_item }}"

    - name: Link configuration to enabled
      file:
        src: /home/ray/{{ item }}.conf
        dest: /home/ray/enabled/{{ item }}.conf
        state: link
      with_items:
      - "{{ all_item }}"
